
# ##########################################################
# Package

[package]

authors = [
  "Matt Wilson <matthew@synesis.com.au>",
]
categories = [
  "filesystem",
  "parsing",
]
description = "Path parsing library for Rust"
documentation = "https://docs.rs/libpath"
edition = "2021"
exclude = [
  ".cargo",
  ".github",
  ".vimrc",
  ".vscode",
  "scripts",
  "target",
]
homepage = "https://github.com/synesissoftware/libpath.Rust"
keywords = [
  "filesystem",
  "parsing",
  "path",
]
license = "BSD-3-Clause"
name = "libpath"
readme = "README.md"
repository = "https://github.com/synesissoftware/libpath.Rust"
rust-version = "1.74"
version = "0.0.3"


# ##########################################################
# Targets

[lib]
name = "libpath"
path = "src/lib.rs"

[[bin]]
name = "libver"
path = "test/scratch/libver/main.rs"


# ##########################################################
# Features

[features]

default = [
]


# General features:
#
# - "null-feature" - a feature that has no effect (and, thus, is useful for simplifying driver scripts);

null-feature = []


# Crate-specific features:
#


# ##########################################################
# Dependencies

[dependencies]

fastparse = { version = "0.0.3", default-features = false, features = [
] }


[dev-dependencies]

test_help-rs = { version = "0.2.1" }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

